### PR TITLE
add AWS CLI v.2 toolset to have a possibility of AWS Code integration

### PR DESCRIPTION
**Pull request by vladislav-yevtushenko**
1. In order to install [AWS Toolkit for JetBrains](https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/setup-toolkit.html) the [AWS AWS Command Line Interface](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html) should be installed as a prerequisite. So it is included in Dockerfile steps.

2. The piece of guide added for those who are trying to run the container on Windows hosted docker

### CODE REVIEW

**Comment by rycus86** [comment]
This is excellent, thank you very much!
I'm uncertain if everyone needs AWS cli in their PyCharm, though maybe it's a nice addition. As an alternative, we could make the Dockerfile more extensible, so you could build an image based on this one that installs extra things like unzip and the awscli utilty. The downside is that you'll have to build the image yourself and rebuild it when there's a new version out. Apart from that, it's working all right, this is how I use IDEA pro at work. What are your thoughts on this?

The Windows instructions are perfect, I'd like to get those in anyway. 👌

Thanks a lot!

**Comment by vladislav-yevtushenko** [comment]
Thanks for your comment!
Actually by some reasons I get a 'Permission denied' error when I'm trying to build own Dockerfile based on your:
```
FROM rycus86/pycharm-pro

RUN apt-get update && apt-get install --no-install-recommends -y  unzip 

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
  && unzip awscliv2.zip \ 
  && rm awscliv2.zip \
  && /opt/pycharm/aws/install

CMD [ "/opt/pycharm/bin/pycharm.sh" ]
```

> E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
> The command '/bin/sh -c apt-get update && apt-get install --no-install-recommends -y  unzip' returned a non-zero code: 100

Still investigating...

**Comment by rycus86** [comment]
Ah yes, this is where extension points might work better. At that point the user is `developer`, that's why you get permission issues. Try this:
```
FROM ...
USER root
RUN ...your commands ...
USER developer
```

**Comment by vladislav-yevtushenko** [comment]
It works now. Thanks a lot.
So I reverted Dockerfile back to original. Let's update Readme only?
Thank you!

**Comment by rycus86** [comment]
Excellent, thank you very much!

**Pull request merged**
